version: '3.8'

services:
  libraryit-server:
    build: .
    container_name: libraryit-server
    ports:
      - "1445:445"
    volumes:
      - ./data/ebooks:/libraryit/ebooks
      - ./data/papers:/libraryit/papers
      - ./data/sourcecode:/libraryit/sourcecode
      - ./data/docs:/libraryit/docs
      - ./logs/libraryit.log:/var/log/samba/libraryit.log   # mount file spesifik
    restart: unless-stopped

  libraryit-logger:
    image: alpine:latest
    container_name: libraryit-logger
    depends_on:
      - libraryit-server
    volumes:
      - ./logs/libraryit.log:/var/log/samba/libraryit.log:ro
    command: tail -n +0 -F /var/log/samba/libraryit.log
    restart: unless-stopped