[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   guest ok = no
   hide unreadable = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   
   # Matikan log Samba standar
   enable core files = no
   log file = /dev/null
   syslog = 0
   log level = 0
   
   # Audit hanya menulis ke /tmp agar tidak muncul di volume
   vfs objects = full_audit
   full_audit:prefix = %u|%I|%S
   full_audit:success = connect disconnect open opendir write mkdir rmdir
   full_audit:failure = connect disconnect open opendir write mkdir rmdir
   full_audit:log file = /tmp/audit_raw.log

[ebooks]
   path = /libraryit/ebooks
   read only = no
   valid users = @readonly, @staff
   write list = @staff
   force group = staff
   create mask = 0660
   directory mask = 0770

[papers]
   path = /libraryit/papers
   read only = no
   valid users = @readonly, @staff
   write list = @staff
   force group = staff
   create mask = 0660
   directory mask = 0770

[sourcecode]
   path = /libraryit/sourcecode
   read only = yes
   valid users = @staff
   force group = staff

[docs]
   path = /libraryit/docs
   read only = yes
   valid users = @readonly, @staff
   write list = librarian
   force group = staff
   create mask = 0660
   directory mask = 0770